jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v30
    - run: nix flake check
    timeout-minutes: 20
name: Check with flake
'on':
  pull_request: {}
  push: {}
