concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  mkdocs-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v30
    - name: Build
      run: 'nix build .#documentation

        mkdir -p site

        cp -r result/* site/

        '
    - if: github.ref == 'refs/heads/main'
      name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
    timeout-minutes: 20
name: Deploy MkDocs to GitHub Pages
'on':
  push:
    branches:
    - main
permissions:
  contents: write
